import { db, type Tx } from "../db";
import { isExternal, requirePermission, type Ctx } from "../context";
import { invalid, notFound, precondition } from "../errors";
import { audit } from "../audit";
import { env } from "../env";
import { getCompanySettings } from "../settings";
import { detectSensitiveContent } from "../sensitive";
import { loadTransaction } from "./access";
import { createApproval } from "./approvals";
import { enqueueJob } from "../jobs/queue";
import { integrationMode } from "../integrations/registry";
import { demoOutbox, smtpProvider } from "../integrations/email";
import { sha256Hex } from "../crypto";
import type { Prisma } from "@/generated/prisma/client";

/**
 * Outbound email pipeline (portal messages are separate and internal).
 *
 * A message reaches a recipient only if ALL of these hold:
 *  1. content passes the sensitive-data check (no bank details / SSNs);
 *  2. the recipient is a participant with an email address who has not
 *     turned off email notifications;
 *  3. it was approved by a person with comms.approve_send, or generated by an
 *     enabled automation rule in AUTO_SEND mode using an approved template;
 *  4. external sending is enabled on the server (EXTERNAL_SEND_ENABLED) AND
 *     for the company;
 *  5. it has not been sent before (idempotency key + atomic status claim).
 * Otherwise it is recorded with a BLOCKED, SUPPRESSED or demo status.
 */

export const PORTAL_FOOTER = "\n\n—\nView details securely in your EscrowFlow portal. To stop email notifications, update your notification preferences in the portal.\nWe will never send or change wiring instructions by email. Verify any instructions by calling a phone number you already know.";

export interface DraftInput {
  transactionId: string;
  participantIds: string[];
  subject: string;
  body: string;
  templateId?: string | null;
  ruleId?: string | null;
  createdByType?: "USER" | "AUTOMATION" | "AI";
  idempotencyKey?: string;
}

export async function createOutboundDraft(ctx: Ctx, input: DraftInput, client?: Tx) {
  if (isExternal(ctx)) throw notFound("Transaction");
  requirePermission(ctx, "comms.draft");
  const run = async (c: Tx | typeof db) => {
    const tx = await loadTransaction(ctx, input.transactionId, c);
    if (!input.subject?.trim() || !input.body?.trim()) throw invalid("Subject and message are required.");
    const ids = [...new Set(input.participantIds)];
    if (!ids.length) throw invalid("Choose at least one recipient.");
    const participants = await c.participant.findMany({ where: { id: { in: ids }, transactionId: tx.id, companyId: ctx.companyId } });
    if (participants.length !== ids.length) throw invalid("Recipients must be participants in this file.");
    const deliverable = participants.filter((p) => p.email && p.emailNotifications && !p.unsubscribedAt);
    const suppressed = participants.filter((p) => !deliverable.includes(p)).map((p) => ({ participantId: p.id, name: p.displayName, reason: !p.email ? "No email address" : "Email notifications turned off" }));
    const body = input.body.trim() + PORTAL_FOOTER;
    const sensitive = detectSensitiveContent(`${input.subject}\n${input.body}`);
    const key = input.idempotencyKey ?? `manual:${sha256Hex(`${tx.id}|${ids.sort().join(",")}|${input.subject}|${input.body}|${Date.now()}`).slice(0, 32)}`;
    const msg = await c.outboundMessage.create({
      data: {
        companyId: ctx.companyId,
        transactionId: tx.id,
        ruleId: input.ruleId ?? null,
        templateId: input.templateId ?? null,
        recipientParticipantIds: deliverable.map((p) => p.id),
        recipientEmails: deliverable.map((p) => p.email!.toLowerCase()),
        suppressedRecipients: suppressed.length ? (suppressed as Prisma.InputJsonValue) : undefined,
        subject: input.subject.trim().slice(0, 200),
        body,
        status: sensitive.length ? "BLOCKED" : deliverable.length === 0 ? "SUPPRESSED" : "DRAFT",
        blockedReason: sensitive.length ? `Contains ${sensitive.join(", ")}. Use the controlled process instead of email.` : deliverable.length === 0 ? "No recipient can receive email." : null,
        createdByType: input.createdByType ?? "USER",
        createdById: ctx.userId,
        idempotencyKey: key,
      },
    });
    await audit(ctx, { action: "outbound.drafted", entityType: "OutboundMessage", entityId: msg.id, transactionId: tx.id, summary: `Email ${msg.status === "DRAFT" ? "drafted" : msg.status.toLowerCase()}: "${msg.subject}" to ${deliverable.length} recipient(s)` }, c as Tx);
    return msg;
  };
  if (client) return run(client);
  try {
    return await db.$transaction((t) => run(t));
  } catch (e) {
    if ((e as { code?: string }).code === "P2002" && input.idempotencyKey) {
      return db.outboundMessage.findUniqueOrThrow({ where: { companyId_idempotencyKey: { companyId: ctx.companyId, idempotencyKey: input.idempotencyKey } } });
    }
    throw e;
  }
}

export function outboundBinding(m: { id: string; subject: string; body: string; recipientEmails: unknown }) {
  return { outboundId: m.id, subjectHash: sha256Hex(m.subject), bodyHash: sha256Hex(m.body), recipients: (m.recipientEmails as string[]).slice().sort() };
}

export async function requestSendApproval(ctx: Ctx, outboundId: string) {
  requirePermission(ctx, "comms.draft");
  const m = await db.outboundMessage.findFirst({ where: { id: outboundId, companyId: ctx.companyId } });
  if (!m) throw notFound("Message");
  if (m.status !== "DRAFT") throw precondition(`This message is ${m.status.toLowerCase()}.`);
  return db.$transaction(async (client) => {
    const a = await createApproval(client, ctx, {
      type: "COMMUNICATION_SEND",
      transactionId: m.transactionId,
      title: `Send email: "${m.subject}"`,
      summary: `To ${(m.recipientEmails as string[]).length} recipient(s). Preview: ${m.body.slice(0, 280)}${m.body.length > 280 ? "…" : ""}`,
      subjectType: "OutboundMessage",
      subjectId: m.id,
      binding: { ...outboundBinding(m), recipientCount: (m.recipientEmails as string[]).length },
      bindingKey: outboundBinding(m),
      requiredPermission: "comms.approve_send",
    });
    await client.outboundMessage.update({ where: { id: m.id }, data: { status: "PENDING_APPROVAL", approvalId: a.id } });
    return a;
  });
}

export async function cancelOutbound(ctx: Ctx, outboundId: string) {
  requirePermission(ctx, "comms.draft");
  const m = await db.outboundMessage.findFirst({ where: { id: outboundId, companyId: ctx.companyId } });
  if (!m) throw notFound("Message");
  if (!["DRAFT", "PENDING_APPROVAL", "APPROVED", "BLOCKED", "SUPPRESSED"].includes(m.status)) throw precondition("This message can no longer be cancelled.");
  await db.$transaction(async (client) => {
    await client.outboundMessage.update({ where: { id: m.id }, data: { status: "CANCELLED" } });
    await client.approval.updateMany({ where: { subjectType: "OutboundMessage", subjectId: m.id, status: "PENDING" }, data: { status: "CANCELLED" } });
    await audit(ctx, { action: "outbound.cancelled", entityType: "OutboundMessage", entityId: m.id, transactionId: m.transactionId, summary: `Email cancelled: "${m.subject}"` }, client);
  });
}

/** Queues delivery; the job applies every gate again at send time. */
export async function queueSend(companyId: string, outboundId: string) {
  return enqueueJob("email.send", { outboundId }, { companyId, idempotencyKey: `email.send:${outboundId}`, maxAttempts: 5 });
}

/** Job handler. Re-checks all gates; safe to run more than once. */
export async function deliverOutbound(companyId: string, outboundId: string) {
  const m = await db.outboundMessage.findFirst({ where: { id: outboundId, companyId } });
  if (!m) throw new Error("Outbound message not found for company");
  if (["SENT", "CAPTURED_DEMO", "CANCELLED", "BLOCKED", "SUPPRESSED"].includes(m.status)) return { status: m.status };
  if (m.status !== "APPROVED" && m.status !== "SENDING") return { status: m.status, skipped: "not approved" };
  const settings = await getCompanySettings(companyId);
  const serverOn = env().EXTERNAL_SEND_ENABLED === "true";
  if (!serverOn || !settings.externalSendingEnabled) {
    await db.outboundMessage.update({ where: { id: m.id }, data: { status: "BLOCKED", blockedReason: `External sending is off (${!serverOn ? "server switch" : "company setting"}). Nothing was sent.` } });
    return { status: "BLOCKED" };
  }
  const sensitive = detectSensitiveContent(`${m.subject}\n${m.body}`);
  if (sensitive.length) {
    await db.outboundMessage.update({ where: { id: m.id }, data: { status: "BLOCKED", blockedReason: `Contains ${sensitive.join(", ")}.` } });
    return { status: "BLOCKED" };
  }
  // Atomic claim prevents a second worker or a replay from sending twice.
  const claimed = await db.outboundMessage.updateMany({ where: { id: m.id, status: "APPROVED" }, data: { status: "SENDING" } });
  if (claimed.count === 0 && m.status !== "SENDING") return { status: "already claimed" };
  const mode = await integrationMode(companyId, "EMAIL");
  const provider = mode === "LIVE" || mode === "SANDBOX" ? ((await smtpProvider()) ?? demoOutbox) : demoOutbox;
  try {
    const res = await provider.send({ messageId: m.id, to: m.recipientEmails as string[], subject: m.subject, text: m.body });
    await db.outboundMessage.update({ where: { id: m.id }, data: { status: provider.delivers ? "SENT" : "CAPTURED_DEMO", provider: provider.id, providerMessageId: res.providerMessageId, sentAt: new Date() } });
    return { status: provider.delivers ? "SENT" : "CAPTURED_DEMO" };
  } catch (e) {
    // Leave in SENDING so a retry resumes; the stable Message-ID lets the relay de-duplicate.
    await db.outboundMessage.update({ where: { id: m.id }, data: { error: e instanceof Error ? e.message.slice(0, 300) : "send failed" } });
    throw e;
  }
}

export async function listOutbound(ctx: Ctx, transactionId?: string) {
  if (isExternal(ctx)) return [];
  requirePermission(ctx, "comms.draft");
  return db.outboundMessage.findMany({ where: { companyId: ctx.companyId, ...(transactionId ? { transactionId } : {}) }, orderBy: { createdAt: "desc" }, take: 100 });
}
